### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by ithakaa** [salt-extensions/saltext-zabbix#4]

**Comment by lkubb** [comment]
It's part of the migration of a bunch of modules out of Salt core from 3008.0 onward, which is going a bit slow, but is not abandoned.

There's no dedicated maintainer for this project though (at the moment).

The intention is that people who depend on modules that are affected by this action should step up and maintain the community extension.

**Comment by lkubb** [comment]
Closing this since @q1x has graciously volunteered to take over maintainership, thanks a lot! <3
